### ISSUE TITLE
Crash - happens immediately after a successful RDT scan

### ISSUE THREAD

**Issue by Mstjamush** [onaio/rdt-standard#622]
Crash - happens immediately after a successful RDT scan

Crash Logs
```
11-12 11:33:45.571  7460  7460 E AndroidRuntime: FATAL EXCEPTION: main
		11-12 11:33:45.571  7460  7460 E AndroidRuntime: Process: io.ona.diagnostics.rdt.configurable.id, PID: 7460
		11-12 11:33:45.571  7460  7460 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=49374, result=-1, data=Intent { (has extras) }} to activity {io.ona.diagnostics.rdt.configurable.id/io.ona.rdt.activity.CovidJsonFormActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
		11-12 11:33:45.571  7460  7460 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4491)
		11-12 11:33:45.571  7460  7460 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4534)
		11-12 11:33:45.571  7460  7460 E AndroidRuntime: 	at android.app.ActivityThread.-wrap20(Unknown Source:0)
		11-12 11:33:45.571  7460  7460 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1752)
		11-12 11:33:45.571  7460  7460 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
		11-12 11:33:45.571  7460  7460 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
		11-12 11:33:45.571  7460  7460 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6944)
		11-12 11:33:45.571  7460  7460 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
		11-12 11:33:45.571  7460  7460 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
		11-12 11:33:45.571  7460  7460 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
		11-12 11:33:45.571  7460  7460 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
		11-12 11:33:45.571  7460  7460 E AndroidRuntime: 	at com.vijay.jsonwizard.activities.JsonFormActivity.invokeRefreshLogic(JsonFormActivity.java:2131)
		11-12 11:33:45.571  7460  7460 E AndroidRuntime: 	at com.vijay.jsonwizard.activities.JsonFormActivity.writeValue(JsonFormActivity.java:142)
		11-12 11:33:45.571  7460  7460 E AndroidRuntime: 	at io.ona.rdt.widget.CovidRDTBarcodeFactory.populateRelevantFields(CovidRDTBarcodeFactory.java:85)
		11-12 11:33:45.571  7460  7460 E AndroidRuntime: 	at io.ona.rdt.widget.CovidRDTBarcodeFactory.onActivityResult(CovidRDTBarcodeFactory.java:55)
		11-12 11:33:45.571  7460  7460 E AndroidRuntime: 	at com.vijay.jsonwizard.activities.JsonFormBaseActivity.onActivityResult(JsonFormBaseActivity.java:186)
		11-12 11:33:45.571  7460  7460 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:7599)
		11-12 11:33:45.571  7460  7460 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4487)
		11-12 11:33:45.571  7460  7460 E AndroidRuntime: 	... 9 more
```

**Comment by Mstjamush** [comment]
Please follow the following steps @vincent-karuri @zeeshan-vd 

- Log in to the App
- Pick a client
- Pick RDT
- Record Location and continue
- Continue on the ID page
- Pick Facility and continue
- Scan Barcode
- Successfully scan a valid sample barcode
- Click Continue on the barcode details page

**Comment by vincent-karuri** [comment]
May be related to https://github.com/onaio/rdt-standard/issues/614#issuecomment-727788302.

@Mstjamush could you post an image of the barcode you're using?

**Comment by vincent-karuri** [comment]
@Mstjamush can we close this?

**Comment by vincent-karuri** [comment]
Closing as fixed.
