### ISSUE TITLE
App crashes 

### ISSUE THREAD

**Issue by vincent-karuri** [onaio/rdt-standard#640]
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{io.ona.diagnostics.rdt.configurable.id/io.ona.rdt.activity.CovidJsonFormActivity}: java.lang.ClassCastException: android.view.AbsSavedState$1 cannot be cast to android.widget.CompoundButton$SavedState
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2741)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2802)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1549)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:163)
       at android.app.ActivityThread.main(ActivityThread.java:6363)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)


Caused by java.lang.ClassCastException: android.view.AbsSavedState$1 cannot be cast to android.widget.CompoundButton$SavedState
       at android.widget.CompoundButton.onRestoreInstanceState(CompoundButton.java:542)
       at android.view.View.dispatchRestoreInstanceState(View.java:15777)
       at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3239)
       at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3239)
       at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3239)
       at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3239)
       at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3239)
       at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3239)
       at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3239)
       at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3239)
       at android.view.View.restoreHierarchyState(View.java:15755)
       at androidx.fragment.app.Fragment.restoreViewState(Fragment.java:573)
       at androidx.fragment.app.FragmentStateManager.restoreViewState(FragmentStateManager.java:356)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1201)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
       at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2637)
       at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2589)
       at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
       at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
       at com.vijay.jsonwizard.activities.JsonFormActivity.onStart(JsonFormActivity.java:2067)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1249)
       at android.app.Activity.performStart(Activity.java:6890)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2704)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2802)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1549)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:163)
       at android.app.ActivityThread.main(ActivityThread.java:6363)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
```

on:

Brand: Xiaomi
Model: Redmi 5 Plu
Operating System: Version: 7.1.2

**Comment by vincent-karuri** [comment]
I haven't found this to be an issue on `Pixel 3XL` on Android 7.1.1 so it's unlikely to be an Android platform issue. Also, I don't believe this was the main source of crashes (happened once as opposed to https://github.com/onaio/rdt-standard/issues/641 which was a persistent issue).

This can be deprioritized unless it becomes a persistent issue.
