### ISSUE TITLE
App crash 

### ISSUE THREAD

**Issue by vincent-karuri** [onaio/rdt-standard#641]
```
Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/format/DateTimeFormatter;
       at com.ibm.fhir.model.type.Date.<clinit>(Date.java:28)
       at java.lang.Class.classForName(Class.java)
       at java.lang.Class.forName(Class.java:400)
       at java.lang.Class.forName(Class.java:326)
       at com.ibm.fhir.model.util.ModelSupport.buildModelClassElementInfoMap(ModelSupport.java:364)
       at com.ibm.fhir.model.util.ModelSupport.<clinit>(ModelSupport.java:113)
       at com.ibm.fhir.model.util.ModelSupport.getModelClasses(ModelSupport.java:629)
       at com.ibm.fhir.model.util.JsonSupport.buildElementNameMap(JsonSupport.java:55)
       at com.ibm.fhir.model.util.JsonSupport.<clinit>(JsonSupport.java:41)
       at com.ibm.fhir.model.util.JsonSupport.nonClosingInputStream(JsonSupport.java:181)
       at com.ibm.fhir.model.parser.FHIRJsonParser.parseAndFilter(FHIRJsonParser.java:65)
       at com.ibm.fhir.model.parser.FHIRJsonParser.parse(FHIRJsonParser.java:61)
       at io.ona.rdt.util.DeviceDefinitionProcessor.getDeviceDefinitionBundle(DeviceDefinitionProcessor.java:48)
       at io.ona.rdt.util.DeviceDefinitionProcessor.getInstance(DeviceDefinitionProcessor.java:41)
       at io.ona.rdt.widget.CovidRDTBarcodeFactory.populateRelevantFields(CovidRDTBarcodeFactory.java:87)
       at io.ona.rdt.widget.CovidRDTBarcodeFactory.onActivityResult(CovidRDTBarcodeFactory.java:58)
       at com.vijay.jsonwizard.activities.JsonFormBaseActivity.onActivityResult(JsonFormBaseActivity.java:186)
       at android.app.Activity.dispatchActivityResult(Activity.java:7128)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4187)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4234)
       at android.app.ActivityThread.-wrap20(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1607)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:163)
       at android.app.ActivityThread.main(ActivityThread.java:6363)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

Caused by java.lang.ClassNotFoundException: Didn't find class "java.time.format.DateTimeFormatter" on path: DexPathList[[zip file "/data/app/io.ona.diagnostics.rdt.configurable.id-1/base.apk"],nativeLibraryDirectories=[/data/app/io.ona.diagnostics.rdt.configurable.id-1/lib/arm64, /data/app/io.ona.diagnostics.rdt.configurable.id-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
       at com.ibm.fhir.model.type.Date.<clinit>(Date.java:28)
       at java.lang.Class.classForName(Class.java)
       at java.lang.Class.forName(Class.java:400)
       at java.lang.Class.forName(Class.java:326)
       at com.ibm.fhir.model.util.ModelSupport.buildModelClassElementInfoMap(ModelSupport.java:364)
       at com.ibm.fhir.model.util.ModelSupport.<clinit>(ModelSupport.java:113)
       at com.ibm.fhir.model.util.ModelSupport.getModelClasses(ModelSupport.java:629)
       at com.ibm.fhir.model.util.JsonSupport.buildElementNameMap(JsonSupport.java:55)
       at com.ibm.fhir.model.util.JsonSupport.<clinit>(JsonSupport.java:41)
       at com.ibm.fhir.model.util.JsonSupport.nonClosingInputStream(JsonSupport.java:181)
       at com.ibm.fhir.model.parser.FHIRJsonParser.parseAndFilter(FHIRJsonParser.java:65)
       at com.ibm.fhir.model.parser.FHIRJsonParser.parse(FHIRJsonParser.java:61)
       at io.ona.rdt.util.DeviceDefinitionProcessor.getDeviceDefinitionBundle(DeviceDefinitionProcessor.java:48)
       at io.ona.rdt.util.DeviceDefinitionProcessor.getInstance(DeviceDefinitionProcessor.java:41)
       at io.ona.rdt.widget.CovidRDTBarcodeFactory.populateRelevantFields(CovidRDTBarcodeFactory.java:87)
       at io.ona.rdt.widget.CovidRDTBarcodeFactory.onActivityResult(CovidRDTBarcodeFactory.java:58)
       at com.vijay.jsonwizard.activities.JsonFormBaseActivity.onActivityResult(JsonFormBaseActivity.java:186)
       at android.app.Activity.dispatchActivityResult(Activity.java:7128)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4187)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4234)
       at android.app.ActivityThread.-wrap20(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1607)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:163)
       at android.app.ActivityThread.main(ActivityThread.java:6363)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
```

Brand: Xiaomi
Model: Redmi 5 Plus
Operating System: Version: 7.1.2

**Comment by vincent-karuri** [comment]
Seems related to https://stackoverflow.com/a/57144294/9782187. This particular class was added in Android 8.

**Comment by vincent-karuri** [comment]
Requires configuring [desugaring](https://developer.android.com/studio/write/java8-support) to support Android 8 features on < Android 8 phones.
