### ISSUE TITLE
Scan barcode and Enter RDT manually options don't respond -  on the RDT option. If it responds, App crashes on the the preceding page when a user clicks Continue

### ISSUE THREAD

**Issue by Mstjamush** [onaio/rdt-standard#833]
Scan barcode and Enter RDT manually options don't respond -  on the RDT option. If it responds, App crashes on the the preceding page when a user clicks Continue

**Steps**
1. Select client and navigate to Client Profile
2. Select RDT
3. Click Locate Me, then Continue. 
4. Pick Name of Facility and continue
5. Select Scan barcode (Doesn't respond, and if it does, app crashes on clicking Continue)
6. Select Continue (App crashes)

**Crash Logs**
```
03-02 16:19:17.926 27069 27069 D ViewRootImpl@b77d5ed[OneScanActivity]: ViewPostIme pointer 1
03-02 16:19:17.942 27069 27069 D AndroidRuntime: Shutting down VM
03-02 16:19:17.953 27069 27069 E AndroidRuntime: FATAL EXCEPTION: main
03-02 16:19:17.953 27069 27069 E AndroidRuntime: Process: io.ona.diagnostics.rdt.configurable.id, PID: 27069
03-02 16:19:17.953 27069 27069 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.ona.rdt.util.OneScanHelper$ScanResponse.serialNumber' on a null object reference
03-02 16:19:17.953 27069 27069 E AndroidRuntime: 	at io.ona.rdt.activity.OneScanActivity.setResultAndFinish(OneScanActivity.java:173)
03-02 16:19:17.953 27069 27069 E AndroidRuntime: 	at io.ona.rdt.activity.OneScanActivity.onClick(OneScanActivity.java:204)
03-02 16:19:17.953 27069 27069 E AndroidRuntime: 	at android.view.View.performClick(View.java:6897)
03-02 16:19:17.953 27069 27069 E AndroidRuntime: 	at android.widget.TextView.performClick(TextView.java:12727)
03-02 16:19:17.953 27069 27069 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:26101)
03-02 16:19:17.953 27069 27069 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)
03-02 16:19:17.953 27069 27069 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
03-02 16:19:17.953 27069 27069 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
03-02 16:19:17.953 27069 27069 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6944)
03-02 16:19:17.953 27069 27069 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-02 16:19:17.953 27069 27069 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
03-02 16:19:17.953 27069 27069 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
03-02 16:19:18.336  3643  4157 D Debug   : !@DumpState : SHIP
03-02 16:19:18.336  3643  4157 D Debug   : !@DumpState : debug level:0x4f4c
03-02 16:19:18.336  3643  4157 D Debug   : !@Dumpstate : Finally, system will skip dumpstate
```

**Comment by vincent-karuri** [comment]
is onescan installed on the device?

**Comment by mwkhan1983** [comment]
this seems to work for me on Android 10

**Comment by Mstjamush** [comment]
@vincent-karuri Tested. Issue was OneScan but we will need to inform the user to install OneScan. This was in one of the previous versions.

**Comment by vincent-karuri** [comment]
ok, closing as resolved
